// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsqwcvivdykzmmlmhrvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzcXdjdml2ZHlrem1tbG1ocnZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTA4NDIsImV4cCI6MjA2MTcyNjg0Mn0.k1OGT_28_9qaVu3Ygj-uuIkbmgdpYfRxYqNRiR7t8oQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);